#!/bin/bash

. "/image/scripts/start-utils"
if [ -f /data/.mc-health.env ]; then
  . /data/.mc-health.env
fi

if isTrue "${DISABLE_HEALTHCHECK}"; then
  echo "Healthcheck disabled"
  exit 0
else
  mc-monitor status "${MC_HEALTH_EXTRA_ARGS[@]}" --host "${SERVER_HOST:-localhost}" --port "${SERVER_PORT:-25565}"
  exit $?
fi
